FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

EXPOSE 3000

# Environment for hot reloading
ENV CHOKIDAR_USEPOLLING=true
ENV FAST_REFRESH=true
ENV WDS_SOCKET_HOST=0.0.0.0

# Start React development server
CMD ["npm", "start"]
