version: '3.8'

services:
  # MongoDB Database
  database:
    image: mongo:7.0
    container_name: medimate_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-adminpass}
      MONGO_INITDB_DATABASE: medimate
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - medimate_network

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: medimate_redis
    ports:
      - "6379:6379"
    networks:
      - medimate_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: medimate_api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-adminpass}@database:27017/medimate?authSource=admin
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3001
      - FRONTEND_URL=http://frontend:3000
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - VAPID_EMAIL=${VAPID_EMAIL:-mailto:admin@medimate.com}
    volumes:
      - ./backend:/app
      - ./packages/shared:/shared
      - ./packages/components:/components
      - /app/node_modules
    depends_on:
      - database
      - redis
    networks:
      - medimate_network

  # Frontend React App
  frontend:
    build:
      context: ./packages/web
      dockerfile: Dockerfile.dev
    container_name: medimate_frontend
    command: npm run start:prod
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api
      - REACT_APP_VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./packages/web:/app
      - ./packages/shared:/shared
      - ./packages/components:/components
      - medimate_web_node_modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - medimate_network

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: medimate_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - medimate_network

  # React Native Metro bundler (for development)
  mobile:
    build:
      context: ./packages/mobile
      dockerfile: Dockerfile.dev
    container_name: medimate_mobile
    ports:
      - "8081:8081"  # Metro bundler port
    environment:
      - API_URL_DEV=${MOBILE_API_URL:-http://backend:3001}
    volumes:
      - ./packages/mobile:/app
      - ./packages/shared:/shared
      - ./packages/components:/components
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - medimate_network
    command: npx react-native start

volumes:
  mongo_data:
  medimate_web_node_modules:

networks:
  medimate_network:
    driver: bridge
